[phases.setup]
cmds = [
    "apt update",
    "apt upgrade -y",
    "sudo apt install curl -y",
    "curl --proto '=https' --tlsv1.3 https://sh.rustup.rs -sSf | sh",
    "source $HOME/.cargo/env",
    "apt install clang libclang-dev llvm build-essential cmake pkg-config libssl-dev ca-certificates libstdc++6 libstdc++-12-dev libc6-dev -y",
    "apt install nettle-dev -y",
    # "/configure --prefix=/usr/ && make && make install",
]
nixpkgs = [
    "rust-bin.stable.latest.default",
    "rustc",
    "cargo",
    "llvmPackages.libclang",
    "libstdcxx5",
    "gcc",
    "glibc",
]

[phases.build]
cmds = ["cargo build --release"]

[start]
cmd = "./target/release/main"
