[variables]
PKG_CONFIG_PATH = "/nix/store"

[phase.name]
aptPkgs = [
    'wget',
    "clang",
    "llvm",
    "pkg-config",
    "nettle-dev",
    "nettle",
    "nettle-devel",
    "cmake",
    "pkgconfig",
]

[phases.setup]
nixpkgs = [
    "pkg-config",
    "nettle",
    "clang",
    "binutils",
    "gcc",
    "rust-bin.stable.latest.default",
    "rustc",
    "cargo",
]

[phases.install]
cmds = ["cargo fetch"]

[phases.build]
cmds = ["cargo build --release"]

[start]
cmd = "./target/release/main"
