[phases.setup]
nixpkgs = [
    "binutils",
    "gcc",
    "pkg-config",
    "nettle.dev",
    "clang",
    "rust-bin.stable.latest.default",
    "rustc",
    "cargo",
]

[phases.install]
cmds = ["cargo fetch"]

[phases.build]
cmds = ["cargo build --release"]

[start]
cmd = "./target/release/main"
