[phases.setup]
cmds = [
    "apt update",
    "apt upgrade -y",
    "apt install clang libclang-dev llvm pkg-config nettle-dev libstdc++6 libstdc++-12-dev libc6-dev cmake build-essential -y",
    # "/configure --prefix=/usr/ && make && make install",
]
nixpkgs = [
    "rust-bin.stable.latest.default",
    "rustc",
    "cargo",
    "llvmPackages.libclang",
    "libstdcxx5",
    "gcc",
    "glibc",
]

[phases.build]
cmds = ["cargo build --release"]

[start]
cmd = "./target/release/main"
