[phases.setup]
nixpkgs = ["rust-bin.stable.latest.default", "rustc", "cargo"]

[phases.install]
cmds = [
    "apt install clang llvm pkg-config nettle-dev pkg-config cmake -y",
    "/configure --prefix=/usr/ && make && make install",
    "cargo fetch",
]

[phases.build]
cmds = ["cargo build --release"]

[start]
cmd = "./target/release/main"
