# [variables]
# PKG_CONFIG_PATH = "/nix/store"

[phase.name]
aptPkgs = [
    'wget',
    "clang",
    "llvm",
    "pkg-config",
    "nettle-dev",
    "nettle",
    "nettle-devel",
    "cmake",
    "pkgconfig",
]

[phases.setup]
nixpkgs = [
    "pkg-config",
    "binutils",
    "gcc",
    "rust-bin.stable.latest.default",
    "rustc",
    "cargo",
    "cmake",
    "nettle.dev",
]

[phases.install]
cmds = [
    "apt install clang llvm pkg-config nettle-dev",
    "/configure --prefix=/usr/ && make && make install",
    "cargo fetch",
]

[phases.build]
cmds = ["cargo build --release"]

[start]
cmd = "./target/release/main"
