[phases.setup]
nixPkgs = ["bun"]

[phases.install]
cmds = ["bun install"]
workingDirectory = "packages/server"

[phases.build]
cmds = ["bun run build"]
workingDirectory = "packages/server"

[start]
cmd = "bun run start"
