export const ERC721_ABI = [
	{
		name: "ownerOf",
		type: "function",
		stateMutability: "view",
		inputs: [{ name: "tokenId", type: "uint256" }],
		outputs: [{ type: "address" }],
	},
	{
		name: "balanceOf",
		type: "function",
		stateMutability: "view",
		inputs: [{ name: "owner", type: "address" }],
		outputs: [{ type: "uint256" }],
	},
	{
		name: "tokenURI",
		type: "function",
		stateMutability: "view",
		inputs: [{ name: "tokenId", type: "uint256" }],
		outputs: [{ type: "string" }],
	},
	{
		name: "supportsInterface",
		type: "function",
		stateMutability: "view",
		inputs: [{ name: "interfaceId", type: "bytes4" }],
		outputs: [{ type: "bool" }],
	},
	{
		name: "name",
		type: "function",
		stateMutability: "view",
		inputs: [],
		outputs: [{ type: "string" }],
	},
	{
		name: "symbol",
		type: "function",
		stateMutability: "view",
		inputs: [],
		outputs: [{ type: "string" }],
	},
	{
		name: "approve",
		type: "function",
		stateMutability: "nonpayable",
		inputs: [
			{ name: "to", type: "address" },
			{ name: "tokenId", type: "uint256" },
		],
		outputs: [],
	},
	{
		name: "getApproved",
		type: "function",
		stateMutability: "view",
		inputs: [{ name: "tokenId", type: "uint256" }],
		outputs: [{ type: "address" }],
	},
	{
		name: "transferFrom",
		type: "function",
		stateMutability: "nonpayable",
		inputs: [
			{ name: "from", type: "address" },
			{ name: "to", type: "address" },
			{ name: "tokenId", type: "uint256" },
		],
		outputs: [],
	},
	{
		name: "safeTransferFrom",
		type: "function",
		stateMutability: "nonpayable",
		inputs: [
			{ name: "from", type: "address" },
			{ name: "to", type: "address" },
			{ name: "tokenId", type: "uint256" },
		],
		outputs: [],
	},
	{
		name: "safeTransferFrom",
		type: "function",
		stateMutability: "nonpayable",
		inputs: [
			{ name: "from", type: "address" },
			{ name: "to", type: "address" },
			{ name: "tokenId", type: "uint256" },
			{ name: "data", type: "bytes" },
		],
		outputs: [],
	},
];
